import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ModeToggle } from "@/components/ui/theme-toggle";
import { pages } from "@/utils/constants";
import Menu from "@/components/ui/main-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={clsx(inter.className, "min-h-screen w-screen font-sans antialiased")}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="relative flex flex-col min-h-screen">
                        <nav className="sticky top-0 flex flex-row  gap-6 px-10 py-4 bg-background/60 backdrop-blur border-b-2 border-secondary">
                            <Menu pages={pages} />
                            <span className="flex-grow"></span>
                            <ModeToggle />
                        </nav>
                        <main className="w-[100%] md:w-[80%] 2xl:w-[60%] m-auto">
                            <div className="border border-secondary p-6 rounded-md">
                                {children}
                            </div>
                        </main>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
